---
title: "R Notebook"
output: html_notebook
---
#library
```{r}
library(ggplot2)
```
 
#import the data set
```{r}
bikesharing_dataset=read.csv("day.csv")
bikesharing_dataset
```
```{r}
head(bikesharing_dataset,5)
```
```{r}
summary(bikesharing_dataset)
```
#finding null values
```{r}
colSums(is.na(bikesharing_dataset))
```
#data visualisation
```{r}
library(ggplot2)
```

```{r}
ggplot(bikesharing_dataset, aes(x = dteday, y = cnt)) +
  geom_point(colour="blue") +
  ggtitle("Scatter plot of dteday vs cnt")
```
```{r}
unique(bikesharing_dataset$workingday)
```
#histogram
```{r}
ggplot(bikesharing_dataset, aes(x = cnt)) + 
  geom_histogram(fill= "blue" ,colour="black", bins = 30) +
  labs(title = "Histogram of cnt",
       x = "Count",
       y = "Frequency")
```
#boxplot
```{r}
ggplot(bikesharing_dataset, aes(x = "", y = cnt)) + 
  geom_boxplot(fill = "blue", color = "black") +
  labs(title = "Boxplot of cnt",
       x = "",
       y = "Count")
```
#regression analysis
```{r}
model <- lm(cnt ~ 1, data = bikesharing_dataset)
summary(model)
```

